spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skill?currentSchema=talent_exchange
    username: skill
    password: skill
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
          client:
            RestTemplate: DEBUG
