spring:
  application:
    name: skills
  jackson:
    default-property-inclusion: NON_EMPTY
    visibility:
      FIELD: any
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %X{traceId}%clr(%m){faint}%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p ${PID} --- [%8.15t] %-40.40logger{0} : %X{traceId}%m%n"
